"""replace image to string

Revision ID: 1879d593ac9f
Revises: 49fcbc52a0a5
Create Date: 2023-03-27 20:11:47.349242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1879d593ac9f'
down_revision = '49fcbc52a0a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_identifiant',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=60),
               type_=sa.String(length=60, collation='utf8_bin'),
               existing_nullable=True)
        batch_op.alter_column('user_profile_picture',
               existing_type=sa.BLOB(),
               type_=sa.String(length=600),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_profile_picture',
               existing_type=sa.String(length=600),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.alter_column('user_identifiant',
               existing_type=sa.String(length=60, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=60),
               existing_nullable=True)

    # ### end Alembic commands ###
