"""adding profile_picture to user table

Revision ID: 1ee2349a0b49
Revises: 9d97a4b3f851
Create Date: 2023-03-27 19:17:01.838087

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ee2349a0b49'
down_revision = '9d97a4b3f851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_profile_picture', sa.LargeBinary(), nullable=True))
        batch_op.alter_column('user_identifiant',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=60),
               type_=sa.String(length=60, collation='utf8_bin'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_identifiant',
               existing_type=sa.String(length=60, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=60),
               existing_nullable=True)
        batch_op.drop_column('user_profile_picture')

    # ### end Alembic commands ###
