"""Change User-Contracts relationship to One To Many

Revision ID: 2c2bea6b69c4
Revises: d7b96cb36559
Create Date: 2023-03-22 06:24:47.476324

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c2bea6b69c4'
down_revision = 'd7b96cb36559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_table',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contract_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], name='association_table_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='association_table_ibfk_1'),
    sa.PrimaryKeyConstraint('user_id', 'contract_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
