"""removing user_username

Revision ID: 4cddfe764f5f
Revises: fb31b38ff783
Create Date: 2023-03-18 19:03:55.760583

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4cddfe764f5f'
down_revision = 'fb31b38ff783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('user_username')
        batch_op.drop_column('user_username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_username', mysql.VARCHAR(length=60), nullable=True))
        batch_op.create_index('user_username', ['user_username'], unique=False)

    # ### end Alembic commands ###
