"""adding creation date and popularity for contract

Revision ID: b57f5a31d282
Revises: c21835987b98
Create Date: 2023-03-26 20:29:50.827193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b57f5a31d282'
down_revision = 'c21835987b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_date_creation', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('contract_popularity', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_identifiant',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=60),
               type_=sa.String(length=60, collation='utf8_bin'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_identifiant',
               existing_type=sa.String(length=60, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=60),
               existing_nullable=True)

    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.drop_column('contract_popularity')
        batch_op.drop_column('contract_date_creation')

    # ### end Alembic commands ###
