"""cascade delete

Revision ID: c21835987b98
Revises: 79214ac6e915
Create Date: 2023-03-25 22:00:56.964627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c21835987b98'
down_revision = '79214ac6e915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_identifiant',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=60),
               type_=sa.String(length=60, collation='utf8_bin'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_identifiant',
               existing_type=sa.String(length=60, collation='utf8_bin'),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=60),
               existing_nullable=True)

    # ### end Alembic commands ###
