"""adding contract_entreprise

Revision ID: d7b96cb36559
Revises: 72773b5ff3c4
Create Date: 2023-03-19 14:27:15.160601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7b96cb36559'
down_revision = '72773b5ff3c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_entreprise', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.drop_column('contract_entreprise')

    # ### end Alembic commands ###
