"""adding contrat_name in contract

Revision ID: f9919076866b
Revises: d5bc495a0100
Create Date: 2023-03-22 17:52:07.910062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9919076866b'
down_revision = 'd5bc495a0100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_name', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.drop_column('contract_name')

    # ### end Alembic commands ###
