"""Adding user email

Revision ID: fb31b38ff783
Revises: 
Create Date: 2023-03-17 19:14:41.234288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb31b38ff783'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_username', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('user_email', sa.String(length=60), nullable=True))
        batch_op.create_unique_constraint(None, ['user_email'])
        batch_op.create_unique_constraint(None, ['user_username'])
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', mysql.VARCHAR(length=60), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_email')
        batch_op.drop_column('user_username')

    # ### end Alembic commands ###
