entreprises = {
    "Electricité": {
        "EDF": "https://particulier.edf.fr/fr/accueil.html",
        "Engie": "https://particuliers.engie.fr/",
        "TotalEnergies": "https://www.totalenergies.fr/particuliers",
        "Eni": "https://fr.eni.com/particuliers",
        "Enercoop": "https://www.enercoop.fr/",
        "Iberdrola": "https://www.iberdrola.fr/",
        "ALPIQ": "https://particuliers.alpiq.fr/",
        "Mega Énergie": "https://www.mega-energie.fr/",
        "Ilek": "https://particuliers.ilek.fr/",
        "Ekwateur": "https://ekwateur.fr/",
        "Vattenfall": "https://www.vattenfall.fr/",
        "Ohm Énergie": "https://ohm-energie.com/",
        "Mint Énergie": "https://www.mint-energie.com/Pages/Accueil/accueil.aspx",
    },
    "Gaz": {
        "EDF": "https://particulier.edf.fr/fr/accueil.html",
        "Engie": "https://particuliers.engie.fr/",
        "TotalEnergies": "https://www.totalenergies.fr/particuliers",
        "Eni": "https://fr.eni.com/particuliers",
        "Alterna": "https://www.alterna-energie.fr/",
        "Iberdrola": "https://www.iberdrola.fr/",
        "Antargaz": "https://www.antargaz.fr/",
        "Mega Énergie": "https://www.mega-energie.fr/",
        "Butagaz": "https://www.butagaz.fr/",
        "Dyneff": "https://www.dyneff.fr/",
        "Vattenfall": "https://www.vattenfall.fr/",
        "Mint Énergie": "https://www.mint-energie.com/Pages/Accueil/accueil.aspx",
    },
    "Téléphone": {
        "SFR": "https://www.sfr.fr/",
        "Orange": "https://www.orange.fr/",
        "Bouygues Télécom": "https://www.bouyguestelecom.fr/",
        "Free": "https://www.free.fr/",
        "RED by SFR": "https://www.red-by-sfr.fr/",
        "Sosh": "https://www.sosh.fr/",
        "La Poste Mobile": "https://www.lapostemobile.fr/",
        "Auchan Télécom": "https://www.auchantelecom.fr/fr/",
        "Cdiscount Mobile": "https://www.cdiscount.com/cdiscount-mobile/v-164-0.html",
        "Coriolis Télécom": "http://www.coriolis.com/",
        "NRJ Mobile": "https://www.nrjmobile.fr/fr/",
        "Prixtel": "https://www.prixtel.com/",
    },
    "Internet": {
        "SFR": "https://www.sfr.fr/",
        "Orange": "https://www.orange.fr/",
        "Bouygues Télécom": "https://www.bouyguestelecom.fr/",
        "Free": "https://www.free.fr/",
        "RED by SFR": "https://www.red-by-sfr.fr/",
        "Sosh": "https://www.sosh.fr/",
        "Nordnet": "https://www.nordnet.com/",
    },
    "Assurance animal": {
        "Selfassurance": "https://www.selfassurance.fr/",
        "Kozoo": "https://www.kozoo.eu/",
        "Dalma": "https://www.dalma.co/",
        "Animaux Santé": "https://www.animauxsante.com/",
        "SantéVet": "https://www.santevet.com/",
        "Acheel": "https://www.acheel.com/",
        "ECA Assurance": "https://eca-assurances.com/",
    },
    "Assurance Auto": {
        "Allianz": "https://www.allianz.fr/",
        "Aon": "https://www.aon.com/france/default.jsp",
        "Direct Assurance": "https://www.direct-assurance.fr/",
        "AXA": "https://www.axa.fr/",
        "MACIF": "https://www.macif.fr/",
        "MAIF": "https://www.maif.fr/",
        "Matmut": "https://www.matmut.fr/",
        "MMA": "https://www.mma.fr/",
        "BNP Paribas": "https://mabanque.bnpparibas/",
        "Gan Assurance": "https://www.gan.fr/",
        "Société Générale": "https://www.assurances.societegenerale.com/fr/particulier/",
        "Crédit Agricole": "https://www.ca-assurances.com/",
        "Caisse d'Épargne": "https://www.caisse-epargne.fr/assurer/",
        "Le Crédit Lyonnais": "https://www.lcl.fr/assurances",
        "ASSU 2000": "https://www.assu2000.fr/",
        "Assurauto": "https://www.assurauto.fr/",
        "Assurpeople": "https://www.assurpeople.com/",
        "La France Mutualiste": "https://www.la-france-mutualiste.fr/",
        "MAAF": "https://www.maaf.fr/fr/espace-client",
        "Groupama": "https://www.groupama.fr/",
    },
    "Assurance Maison": {
        "Groupama": "https://www.groupama.fr/",
        "Allianz": "https://www.allianz.fr/",
        "Aon": "https://www.aon.com/france/default.jsp",
        "Direct Assurance": "https://www.direct-assurance.fr/",
        "AXA": "https://www.axa.fr/",
        "MACIF": "https://www.macif.fr/",
        "MAIF": "https://www.maif.fr/",
        "Matmut": "https://www.matmut.fr/",
        "MMA": "https://www.mma.fr/",
        "BNP Paribas": "https://mabanque.bnpparibas/",
        "Gan Assurance": "https://www.gan.fr/",
        "Société Générale": "https://www.assurances.societegenerale.com/fr/particulier/",
        "Crédit Agricole": "https://www.ca-assurances.com/",
        "Caisse d'Épargne": "https://www.caisse-epargne.fr/assurer/",
        "Le Crédit Lyonnais": "https://www.lcl.fr/assurances",
        "La France Mutualiste": "https://www.la-france-mutualiste.fr/",
        "MAAF": "https://www.maaf.fr/fr/espace-client",
    },
}
